### ISSUE TITLE
Unit test produces segmentation fault

### ISSUE THREAD

**Issue by chayandashora** [cbsiddharth/libosdp#2]
Below is the terminal output:

`chayandashora@linux-ggds:~/Downloads/libosdp_master_sid/build> make && make check`
`[100%] Built target osdp`
`[100%] Built target osdpctl`
`[100%] Built target osdp`
`[100%] Built target osdp-test`
`------------------------------------------`
            `OSDP - Unit Tests`             
`------------------------------------------`
`Testing cp_build_packet(CMD_POLL) -- success!`
`Testing cp_build_packet(CMD_ID) -- success!`
`Testing phy_decode_packet(REPLY_ACK) -- success!`
`Testing cp_queue_command() -- success!`

`Starting CP fsm state tests`
    `-- executing test_cp_phy_fsm()`
`make[3]: *** [CMakeFiles/check.dir/build.make:57: CMakeFiles/check] Segmentation fault (core dumped)`
`make[2]: *** [CMakeFiles/Makefile2:68: CMakeFiles/check.dir/all] Error 2`
`make[1]: *** [CMakeFiles/Makefile2:75: CMakeFiles/check.dir/rule] Error 2`
`make: *** [Makefile:164: check] Error 2`

Upon further analysis, I found out that in test/test-cp-phy-fsm.c, line 126,
`while (result) {`
if the result value is 1, then segmentation fault appears.

**Comment by cbsiddharth** [comment]
@chayandashora, thanks for reporting this issue. Can you provide some information on your dev environment? I'm unable to reproduce it in my Mac or Centos-7 VM. Besides, the CI is building this on ubuntu (trusty) without this issue.

**Comment by chayandashora** [comment]
@cbsiddharth 
I am running OpenSuse Leap 15.1 on Oracle Virtual Box

**Comment by cbsiddharth** [comment]
@chayandashora, I think this issue is now fixed. Please let me know if it persists.
