### ISSUE TITLE
executable name same as directory name

### ISSUE THREAD

**Issue by z8a** [cbsiddharth/libosdp#3]
Compiling on Linux there is a linker error: /usr/bin/ld: cannot open output file osdpctl: Is a directory.

**Comment by cbsiddharth** [comment]
@z8a, I think you did a `cmake .` on the root of the repo. This will cause an issue as osdpctl is a directory and it is the name of the binary. Please try:

```
mkdir build && cd build
cmake ..
make
```

**Comment by z8a** [comment]
You are right, it's written in README.md! Thank you.
