### ISSUE TITLE
osdp_pd_setup doesn't use osdp_pd_info_t.flags field

### ISSUE THREAD

**Issue by z8a** [cbsiddharth/libosdp#5]
When osdp_pd_setup is called the value of flags field is ignored.

**Comment by cbsiddharth** [comment]
@z8a, thanks for reporting this issue. Are you using this flags field? I was planning on deprecating it as none of the flag masks are exposed through osdp.h anymore. If what you are doing is a common requirement, then I can enable proper a API for it.

For now, I have fixed it.
