### ISSUE TITLE
AES-128 padding for packet length % 16 == 0

### ISSUE THREAD

**Issue by z8a** [cbsiddharth/libosdp#6]
In OSDP V2 1_6_2014 - Appendix D.4.5 Padding is specified that
padding is necessary also if the data block is multiple of 16.
At the moment in the library there is no padding if length % 16 == 0.

**Comment by cbsiddharth** [comment]
@z8a, Acknowledged. Thanks again, great find.

**Comment by z8a** [comment]
I've reported your modifies on my firmware but they aren't working. I was not able to understand why.

**Comment by cbsiddharth** [comment]
What is the issue you are facing? Can you paste the logs produced by this library with loglevel set to DEBUG?

**Comment by cbsiddharth** [comment]
@z8a, Are you still facing this issue? or have you resolved it? You need to provide some additional information if you'd like me to look into it.
