### ISSUE TITLE
REPLY_COM structure has address missing

### ISSUE THREAD

**Issue by z8a** [cbsiddharth/libosdp#8]
According specification it should be:	
          case REPLY_COM:
		buf[len++] = reply->id;
                buf[len++] = p->address;
		buf[len++] = byte_0(p->baud_rate);
		buf[len++] = byte_1(p->baud_rate);
		buf[len++] = byte_2(p->baud_rate);
		buf[len++] = byte_3(p->baud_rate);
		break;

**Comment by cbsiddharth** [comment]
@z8a, Thanks for reporting.
